# netlify.toml

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Single-page app fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Cache hashed assets for a long time
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Serve the web app manifest with the right MIME type
# (Change to /manifest.webmanifest if that's your filename)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache"

# Ensure the service worker is always revalidated
# (vite-plugin-pwa outputs /sw.js by default)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Optional: simple security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options        = "DENY"
    Referrer-Policy        = "strict-origin-when-cross-origin"
